site_name: The Infinite Black 2 Wiki (unofficial)
site_url: https://gatorskull.github.io/tib2-wiki/
repo_url: https://github.com/gatorskull/tib2-wiki
repo_name: Contribute

theme:
  name: material
  features:
    - navigation.instant  # Click links without page reloads
    - navigation.tracking # Updates URL as you scroll
    # - navigation.sections  <-- REMOVED: This was forcing folders to stay open as headers!
  palette:
    scheme: slate
    primary: deep purple
    accent: cyan

plugins:
  - search
  - section-index      
  - awesome-pages

markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - wikilinks